spring:
  application:
    name: housing

  datasource:
    url: jdbc:postgresql://ep-soft-breeze-aicyu3ti-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_LUdo0XrRWbI7
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

 
  mail:
    host: smtp.gmail.com
    port: 587
    username: imsharlok@gmail.com
    password: vfgk gfek riwm lbjh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.backend.housing: DEBUG


app:
  default-profile-picture: "https://ui-avatars.com/api/?name=User&background=6366f1&color=fff&size=200"

supabase:

    url: ${SUPABASE_URL}
    key: ${SUPABASE_KEY}
    bucket: property-images

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  success-url: http://localhost:3000/payment/success
  cancel-url: http://localhost:3000/payment/cancel
  url: ${SUPABASE_URL:http://localhost:54321}
  key: ${SUPABASE_KEY:default-key}
  bucket: property-images
