package com.backend.housing.domain.entity.notifications.enums;

public enum NotificationType {
    CONTRACT_ACTIVATED,
    PAYMENT_REMINDER,
    CONTRACT_EXPIRED,
    PAYMENT_SUCCEEDED,
    CONTRACT_TERMINATED,
    CONTRACT_CANCELLED,
    CONTRACT_CANCELLATION_SCHEDULED,
    REQUEST_ACCEPTED,
    REQUEST_REJECTED,
    REQUEST_SEND

}